Total Sales = SUM('sales_summary'[total_sales])

Active Customers = SUM('sales_summary'[active_customers])

Order Count = SUM('sales_summary'[order_count])

Average Sales per Customer = DIVIDE([Total Sales], [Active Customers])

Average Discount % = AVERAGE('sales_summary'[average_discount_pct])

Lifetime Sales = SUM('customer_360'[lifetime_sales])

Support Tickets = SUM('customer_360'[support_ticket_count])

Average Satisfaction = AVERAGE('customer_360'[average_satisfaction_score])

Critical Tickets = SUM('customer_360'[critical_ticket_count])

Customer Count = DISTINCTCOUNT('customer_360'[customer_id])
