table sales_summary
	lineageTag: 1d038524-961c-4649-afc1-60a39286706e

	measure 'Total Sales' = SUM('sales_summary'[total_sales])
		formatString: \$#,0;(\$#,0)

	measure 'Active Customers' = SUM('sales_summary'[active_customers])
		formatString: #,0

	measure 'Order Count' = SUM('sales_summary'[order_count])
		formatString: #,0

	measure 'Average Sales per Customer' = DIVIDE([Total Sales], [Active Customers])
		formatString: \$#,0;(\$#,0)

	measure 'Average Discount %' = AVERAGE('sales_summary'[average_discount_pct])
		formatString: 0.0%

	column geo
		dataType: string
		summarizeBy: none
		sourceColumn: geo

		annotation SummarizationSetBy = Automatic

	column sales_region
		dataType: string
		summarizeBy: none
		sourceColumn: sales_region

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		summarizeBy: none
		sourceColumn: industry

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column sales_year
		dataType: int64
		summarizeBy: none
		sourceColumn: sales_year

		annotation SummarizationSetBy = Automatic

	column sales_month
		dataType: int64
		summarizeBy: none
		sourceColumn: sales_month

		annotation SummarizationSetBy = Automatic

	column total_sales
		dataType: double
		summarizeBy: sum
		sourceColumn: total_sales

		annotation SummarizationSetBy = Automatic

	column active_customers
		dataType: int64
		summarizeBy: sum
		sourceColumn: active_customers

		annotation SummarizationSetBy = Automatic

	column order_count
		dataType: int64
		summarizeBy: sum
		sourceColumn: order_count

		annotation SummarizationSetBy = Automatic

	column average_discount_pct
		dataType: double
		summarizeBy: average
		sourceColumn: average_discount_pct

		annotation SummarizationSetBy = Automatic

	partition sales_summary = entity
		mode: directLake
		source
			entityName: sales_summary
			schemaName: dbo
			expressionSource: 'DirectLake - LH_Gold'

	annotation PBI_ResultType = Table
